### ISSUE TITLE
Entrypoint does not exist

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [mxsdev/nvim-dap-vscode-js#31]
Could it be that this go renamed to just debugServer.js?
https://github.com/mxsdev/nvim-dap-vscode-js/blob/b6d247eb0faca30cd01adc84594a6d44d6026abc/lua/dap-vscode-js/utils.lua#L53

**Comment by sschneider-ihre-pvs** [comment]
oh the default path was just off since I am using Lazy.

**Comment by sschneider-ihre-pvs** [comment]
ok, the debugger_path has problems with windows paths

**Comment by sschneider-ihre-pvs** [comment]
`...\opt\vscode-js-debug\out/src/vsDebugServer.js` mixed / and \

**Comment by sschneider-ihre-pvs** [comment]
arg different error again :D

**Comment by IzioDev** [comment]
How did you solve this issue @sschneider-ihre-pvs ?

I installed js dap server using Mason, located in `/home/romain/.local/share/nvim/mason/packages/js-debug-adapter/`.

I'm using Lazy too, what did you ended up with?

**Comment by ungrim97** [comment]
Newer versions of the vscode-js-debug seem to have alternate builds. 

Mason uses the dapDebugServer build rather than the older vsDebugServer. This means that for versions after 1.76.1 of vscode-js-debug there is no '/out/src/vsDebugServer.js', instead the path is Entrypoint path is now `js-debug/src/dapDebugServer.js`

I suspect the easiest thing will be to update to allow a configurable entry point relative to the debugger_path.

For now those using mason-dap-nvim to install vscode-js-debug can use version 1.76.1 instead of the latest 1.82
