### ISSUE TITLE
vscode-js-debug build process has changed causing errors on fresh install

### ISSUE THREAD

**Issue by MadeByJay** [mxsdev/nvim-dap-vscode-js#33]
Just spent about 2 hours trying to get nvim-dap-vscode-js up and running but kept running into an error after installing and compiling says that `/out/src/vsDebugServer.js` couldn't be found. Again this was after npm install & compiling several times. 

Finally checked out the gulp.js file for vscode-js-debug and the build process has recently changed. If anyone tries to follow the readme for this plugin now they'll fail just because the build process was switched out. 

The temp fix for this is to set vscode-js-debug to a working commit-hash with whatever plugin installer you're using. I believe the one from Feb 24th works still.

**Comment by mxsdev** [comment]
Hi,

Thanks for pointing this out, I will take a look later today!

**Comment by mxsdev** [comment]
Ok, looks like you need to run:

```
npx gulp vsDebugServerBundle
```

And the resulting file will be in `dist` rather than `out`. Looks like it's hard-coded :( which is unfortunate because I (in retrospect, rather stupidly) also hard-coded the folder structure.

For now I guess I'll just add a line to the script that renames `dist` to `out`, so the new script will be:

`npm install && npx gulp vsDebugServerBundle && mv dist out`

Let me know if this new script works for you @MadeByJay. If so I'll change the README and add a notice.

**Comment by MadeByJay** [comment]
The new script works. Tried it out on a fresh nvim install and received no errors. Thanks for taking a look!
